### ISSUE TITLE
Both shards must move.

### ISSUE THREAD

**Issue by langbenjf** [foolswood/Hexagongame#19]
If either shard has never been moved the "win" message does not come up.

I have checked to see if the types of numbers (ints, floats) set in the positions are different when the maze is set up vs. when positions update, but it looks good to me. I can't spot the problem; although I think it didn't exist previously and has arisen since the "allEqual" function was introduced.

**Comment by foolswood** [comment]
Turns out in JS `[3, 0] === [3, 0] -> false` wheras `a === a -> true`, it works when you move because they get set to the same coordinate object instance.

**Comment by foolswood** [comment]
Fixed on the branch.
