### ISSUE TITLE
Maze resetting can return to the menu immediately

### ISSUE THREAD

**Issue by foolswood** [foolswood/Hexagongame#2]
When the marker is clicked to return to the start position it doesn't always go there, sometimes it goes to the menu instead.

I suspect this is to do with changing to addEventListener instead of onclick, it'll need some kind of removal code.

**Comment by foolswood** [comment]
It was occurring in safari for mac, so whilst I believe it is fixed it requires testing on such a system.

**Comment by johnaldis** [comment]
Seems to work for me (on Safari for Mac).
