### ISSUE TITLE
Sorry! - Merged "backwards"

### ISSUE THREAD

**Issue by langbenjf** [foolswood/Hexagongame#8]
It seems I still don't understand Github.

I was attempting to use a "pull request" to get your updated code onto my version of the project. I appear to have instead put my mazes onto your version.

**Comment by foolswood** [comment]
New mazes, cool!

I can put it back how it was and try and do it again, more intentionally forwards, or tidy from where it landed.

**Comment by foolswood** [comment]
I had a go at building the history that I think you were going for over in #10. Have a peer and let me know if I'm on the right lines.

**Comment by foolswood** [comment]
Sorted
